name: Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build
        run: ./scripts/build.sh

      - name: Build with mmap
        run: ./scripts/build.sh --mmap
        
    #   - name: Test
    #     timeout-minutes: 1
    #     run: ./scripts/test.sh
